services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - /workspace/bin
      - /workspace/obj
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=az-db100;Port=5432;Database=postgres_az;Username=az;Password=azaz"
    ports:
      - "38080:8080"
    depends_on:
      - az-db100
    command: /bin/sh -c "while sleep 1000; do :; done"

  az-db100:
    image: postgres:18
    environment:
      POSTGRES_DB: postgres_az
      POSTGRES_USER: az
      POSTGRES_PASSWORD: azaz
    ports:
      - "35432:5432"
    volumes:
      - az-db100-data:/var/lib/postgresql/data
      - ../sql:/docker-entrypoint-initdb.d

volumes:
  az-db100-data: